namespace FoodDrinkApp.Services;

// Holds the mockapi.io endpoint so FoodCatalogService knows whether to
// fetch from the remote API or fall back to the local seed list.
// Leaving EndpointUrl empty means the app runs fully offline.
public static class MockApiConfig
{
    // Set this to the Resource URL generated by mockapi.io before building for a demo.
    // Example: https://6821a6b0a7b7a.mockapi.io/api/v1/foods
    public const string EndpointUrl = "";

    public static bool IsConfigured => !string.IsNullOrWhiteSpace(EndpointUrl);
}
